sudo: required
services: 
    - docker

before_install:
    - docker build -t subhajit1985/docker-react-aws -f Dockerfile.dev .

script:
    - docker run -e CI=true subhajit1985/docker-react-aws npm run test -- --coverage    

