version: '3'
services: 
    react-app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        stdin_open: true   

        
        # volumes: 
        #     - app/node_modules
        #     - .:/app    